//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4984.
// 
namespace QHMobile.UsersQH {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsersQH_Binding", Namespace="urn:microsoft-dynamics-schemas/page/usersqh")]
    public partial class UsersQH_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UsersQH_Service() {
            this.Url = "http://dpmaster.dptech.local:7045/DynamicsNAVQH/WS/Qian%20Hu/Page/UsersQH";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("UsersQH")]
        public UsersQH Read(string UserName) {
            object[] results = this.Invoke("Read", new object[] {
                        UserName});
            return ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string UserName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        UserName}, callback, asyncState);
        }
        
        /// <remarks/>
        public UsersQH EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("UsersQH")]
        public UsersQH ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string recId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadByRecId", new object[] {
                        recId}, callback, asyncState);
        }
        
        /// <remarks/>
        public UsersQH EndReadByRecId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public UsersQH[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] UsersQH_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((UsersQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(UsersQH_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public UsersQH[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UsersQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref UsersQH UsersQH) {
            object[] results = this.Invoke("Create", new object[] {
                        UsersQH});
            UsersQH = ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(UsersQH UsersQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        UsersQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out UsersQH UsersQH) {
            object[] results = this.EndInvoke(asyncResult);
            UsersQH = ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref UsersQH[] UsersQH_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        UsersQH_List});
            UsersQH_List = ((UsersQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(UsersQH[] UsersQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        UsersQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out UsersQH[] UsersQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            UsersQH_List = ((UsersQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref UsersQH UsersQH) {
            object[] results = this.Invoke("Update", new object[] {
                        UsersQH});
            UsersQH = ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(UsersQH UsersQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        UsersQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out UsersQH UsersQH) {
            object[] results = this.EndInvoke(asyncResult);
            UsersQH = ((UsersQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref UsersQH[] UsersQH_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        UsersQH_List});
            UsersQH_List = ((UsersQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(UsersQH[] UsersQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        UsersQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out UsersQH[] UsersQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            UsersQH_List = ((UsersQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/usersqh:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/usersqh", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/usersqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/usersqh")]
    public partial class UsersQH {
        
        private string keyField;
        
        private string userNameField;
        
        private string passwordField;
        
        private UserLevel userLevelField;
        
        private bool userLevelFieldSpecified;
        
        private string stuff_DimensionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public UserLevel UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserLevelSpecified {
            get {
                return this.userLevelFieldSpecified;
            }
            set {
                this.userLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Stuff_Dimension {
            get {
                return this.stuff_DimensionField;
            }
            set {
                this.stuff_DimensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/usersqh")]
    public enum UserLevel {
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Super,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/usersqh")]
    public partial class UsersQH_Filter {
        
        private UsersQH_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public UsersQH_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/usersqh")]
    public enum UsersQH_Fields {
        
        /// <remarks/>
        UserName,
        
        /// <remarks/>
        Password,
        
        /// <remarks/>
        UserLevel,
        
        /// <remarks/>
        Stuff_Dimension,
    }
}
