//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3623.
// 
namespace RGSMobile.ScanLogin {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ScanLogin_Binding", Namespace="urn:microsoft-dynamics-schemas/page/scanlogin")]
    public partial class ScanLogin_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ScanLogin_Service() {
            this.Url = "http://dpmaster:7047/DynamicsNAV/WS/RGS%20Enterprise%20(UAT)/Page/ScanLogin";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ScanLogin")]
        public ScanLogin Read(string Data_ID, string Source_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Data_ID,
                        Source_No});
            return ((ScanLogin)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string Data_ID, string Source_No, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        Data_ID,
                        Source_No}, callback, asyncState);
        }
        
        /// <remarks/>
        public ScanLogin EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ScanLogin)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanLogin[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] ScanLogin_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ScanLogin[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(ScanLogin_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public ScanLogin[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ScanLogin[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref ScanLogin ScanLogin) {
            object[] results = this.Invoke("Create", new object[] {
                        ScanLogin});
            ScanLogin = ((ScanLogin)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(ScanLogin ScanLogin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        ScanLogin}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out ScanLogin ScanLogin) {
            object[] results = this.EndInvoke(asyncResult);
            ScanLogin = ((ScanLogin)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ScanLogin[] ScanLogin_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        ScanLogin_List});
            ScanLogin_List = ((ScanLogin[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(ScanLogin[] ScanLogin_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        ScanLogin_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out ScanLogin[] ScanLogin_List) {
            object[] results = this.EndInvoke(asyncResult);
            ScanLogin_List = ((ScanLogin[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref ScanLogin ScanLogin) {
            object[] results = this.Invoke("Update", new object[] {
                        ScanLogin});
            ScanLogin = ((ScanLogin)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(ScanLogin ScanLogin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        ScanLogin}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out ScanLogin ScanLogin) {
            object[] results = this.EndInvoke(asyncResult);
            ScanLogin = ((ScanLogin)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ScanLogin[] ScanLogin_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        ScanLogin_List});
            ScanLogin_List = ((ScanLogin[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(ScanLogin[] ScanLogin_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        ScanLogin_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out ScanLogin[] ScanLogin_List) {
            object[] results = this.EndInvoke(asyncResult);
            ScanLogin_List = ((ScanLogin[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/scanlogin:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/scanlogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scanlogin")]
    public partial class ScanLogin {
        
        private string keyField;
        
        private string data_IDField;
        
        private string source_NoField;
        
        private string source_DescriptionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Data_ID {
            get {
                return this.data_IDField;
            }
            set {
                this.data_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Source_No {
            get {
                return this.source_NoField;
            }
            set {
                this.source_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Source_Description {
            get {
                return this.source_DescriptionField;
            }
            set {
                this.source_DescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scanlogin")]
    public partial class ScanLogin_Filter {
        
        private ScanLogin_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public ScanLogin_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/scanlogin")]
    public enum ScanLogin_Fields {
        
        /// <remarks/>
        Data_ID,
        
        /// <remarks/>
        Source_No,
        
        /// <remarks/>
        Source_Description,
    }
}
