//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5456.
// 
namespace QHMobile.WarehouseRequestQH {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WarehouseRequestQH_Binding", Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public partial class WarehouseRequestQH_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WarehouseRequestQH_Service() {
            this.Url = "http://dpmaster.dptech.local:7045/DynamicsNAVQH/WS/Qian%20Hu/Page/WarehouseReques" +
                "tQH";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WarehouseRequestQH")]
        public WarehouseRequestQH Read(string Type, string Location_Code, string Source_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Type,
                        Location_Code,
                        Source_No});
            return ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string Type, string Location_Code, string Source_No, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        Type,
                        Location_Code,
                        Source_No}, callback, asyncState);
        }
        
        /// <remarks/>
        public WarehouseRequestQH EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WarehouseRequestQH")]
        public WarehouseRequestQH ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string recId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadByRecId", new object[] {
                        recId}, callback, asyncState);
        }
        
        /// <remarks/>
        public WarehouseRequestQH EndReadByRecId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WarehouseRequestQH[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] WarehouseRequestQH_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((WarehouseRequestQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(WarehouseRequestQH_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public WarehouseRequestQH[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WarehouseRequestQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref WarehouseRequestQH WarehouseRequestQH) {
            object[] results = this.Invoke("Create", new object[] {
                        WarehouseRequestQH});
            WarehouseRequestQH = ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(WarehouseRequestQH WarehouseRequestQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        WarehouseRequestQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out WarehouseRequestQH WarehouseRequestQH) {
            object[] results = this.EndInvoke(asyncResult);
            WarehouseRequestQH = ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref WarehouseRequestQH[] WarehouseRequestQH_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        WarehouseRequestQH_List});
            WarehouseRequestQH_List = ((WarehouseRequestQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(WarehouseRequestQH[] WarehouseRequestQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        WarehouseRequestQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out WarehouseRequestQH[] WarehouseRequestQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            WarehouseRequestQH_List = ((WarehouseRequestQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref WarehouseRequestQH WarehouseRequestQH) {
            object[] results = this.Invoke("Update", new object[] {
                        WarehouseRequestQH});
            WarehouseRequestQH = ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(WarehouseRequestQH WarehouseRequestQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        WarehouseRequestQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out WarehouseRequestQH WarehouseRequestQH) {
            object[] results = this.EndInvoke(asyncResult);
            WarehouseRequestQH = ((WarehouseRequestQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref WarehouseRequestQH[] WarehouseRequestQH_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        WarehouseRequestQH_List});
            WarehouseRequestQH_List = ((WarehouseRequestQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(WarehouseRequestQH[] WarehouseRequestQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        WarehouseRequestQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out WarehouseRequestQH[] WarehouseRequestQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            WarehouseRequestQH_List = ((WarehouseRequestQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/warehouserequestqh:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public partial class WarehouseRequestQH {
        
        private string keyField;
        
        private string source_NoField;
        
        private Source_Document source_DocumentField;
        
        private bool source_DocumentFieldSpecified;
        
        private Document_Status document_StatusField;
        
        private bool document_StatusFieldSpecified;
        
        private string location_CodeField;
        
        private string shipment_Method_CodeField;
        
        private string shipping_Agent_CodeField;
        
        private Shipping_Advice shipping_AdviceField;
        
        private bool shipping_AdviceFieldSpecified;
        
        private Destination_Type destination_TypeField;
        
        private bool destination_TypeFieldSpecified;
        
        private string destination_NoField;
        
        private string external_Document_NoField;
        
        private System.DateTime expected_Receipt_DateField;
        
        private bool expected_Receipt_DateFieldSpecified;
        
        private System.DateTime shipment_DateField;
        
        private bool shipment_DateFieldSpecified;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string put_away_Pick_NoField;
        
        private bool completely_HandledField;
        
        private bool completely_HandledFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Source_No {
            get {
                return this.source_NoField;
            }
            set {
                this.source_NoField = value;
            }
        }
        
        /// <remarks/>
        public Source_Document Source_Document {
            get {
                return this.source_DocumentField;
            }
            set {
                this.source_DocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_DocumentSpecified {
            get {
                return this.source_DocumentFieldSpecified;
            }
            set {
                this.source_DocumentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Document_Status Document_Status {
            get {
                return this.document_StatusField;
            }
            set {
                this.document_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_StatusSpecified {
            get {
                return this.document_StatusFieldSpecified;
            }
            set {
                this.document_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipment_Method_Code {
            get {
                return this.shipment_Method_CodeField;
            }
            set {
                this.shipment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Agent_Code {
            get {
                return this.shipping_Agent_CodeField;
            }
            set {
                this.shipping_Agent_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Shipping_Advice Shipping_Advice {
            get {
                return this.shipping_AdviceField;
            }
            set {
                this.shipping_AdviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipping_AdviceSpecified {
            get {
                return this.shipping_AdviceFieldSpecified;
            }
            set {
                this.shipping_AdviceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Destination_Type Destination_Type {
            get {
                return this.destination_TypeField;
            }
            set {
                this.destination_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Destination_TypeSpecified {
            get {
                return this.destination_TypeFieldSpecified;
            }
            set {
                this.destination_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Destination_No {
            get {
                return this.destination_NoField;
            }
            set {
                this.destination_NoField = value;
            }
        }
        
        /// <remarks/>
        public string External_Document_No {
            get {
                return this.external_Document_NoField;
            }
            set {
                this.external_Document_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Expected_Receipt_Date {
            get {
                return this.expected_Receipt_DateField;
            }
            set {
                this.expected_Receipt_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Expected_Receipt_DateSpecified {
            get {
                return this.expected_Receipt_DateFieldSpecified;
            }
            set {
                this.expected_Receipt_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Shipment_Date {
            get {
                return this.shipment_DateField;
            }
            set {
                this.shipment_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_DateSpecified {
            get {
                return this.shipment_DateFieldSpecified;
            }
            set {
                this.shipment_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Put_away_Pick_No {
            get {
                return this.put_away_Pick_NoField;
            }
            set {
                this.put_away_Pick_NoField = value;
            }
        }
        
        /// <remarks/>
        public bool Completely_Handled {
            get {
                return this.completely_HandledField;
            }
            set {
                this.completely_HandledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Completely_HandledSpecified {
            get {
                return this.completely_HandledFieldSpecified;
            }
            set {
                this.completely_HandledFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public enum Source_Document {
        
        /// <remarks/>
        Sales_Order,
        
        /// <remarks/>
        Sales_Return_Order,
        
        /// <remarks/>
        Purchase_Order,
        
        /// <remarks/>
        Purchase_Return_Order,
        
        /// <remarks/>
        Inbound_Transfer,
        
        /// <remarks/>
        Outbound_Transfer,
        
        /// <remarks/>
        Prod_Consumption,
        
        /// <remarks/>
        Prod_Output,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public enum Document_Status {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Released,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public enum Shipping_Advice {
        
        /// <remarks/>
        Partial,
        
        /// <remarks/>
        Complete,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public enum Destination_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Vendor,
        
        /// <remarks/>
        Location,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Family,
        
        /// <remarks/>
        Sales_Order,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public enum Type {
        
        /// <remarks/>
        Inbound,
        
        /// <remarks/>
        Outbound,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public partial class WarehouseRequestQH_Filter {
        
        private WarehouseRequestQH_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public WarehouseRequestQH_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/warehouserequestqh")]
    public enum WarehouseRequestQH_Fields {
        
        /// <remarks/>
        Source_No,
        
        /// <remarks/>
        Source_Document,
        
        /// <remarks/>
        Document_Status,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Shipment_Method_Code,
        
        /// <remarks/>
        Shipping_Agent_Code,
        
        /// <remarks/>
        Shipping_Advice,
        
        /// <remarks/>
        Destination_Type,
        
        /// <remarks/>
        Destination_No,
        
        /// <remarks/>
        External_Document_No,
        
        /// <remarks/>
        Expected_Receipt_Date,
        
        /// <remarks/>
        Shipment_Date,
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        Put_away_Pick_No,
        
        /// <remarks/>
        Completely_Handled,
    }
}
