//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5466.
// 
namespace QHMobile.QHWarehouseEntry {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QHWarehouseEntry_Binding", Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public partial class QHWarehouseEntry_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public QHWarehouseEntry_Service() {
            this.Url = "http://dpmaster.dptech.local:7045/DynamicsNAVQH/WS/Qian%20Hu/Page/QHWarehouseEntr" +
                "y";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("QHWarehouseEntry")]
        public QHWarehouseEntry Read(int Entry_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Entry_No});
            return ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(int Entry_No, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        Entry_No}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHWarehouseEntry EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("QHWarehouseEntry")]
        public QHWarehouseEntry ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string recId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadByRecId", new object[] {
                        recId}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHWarehouseEntry EndReadByRecId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public QHWarehouseEntry[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] QHWarehouseEntry_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((QHWarehouseEntry[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(QHWarehouseEntry_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHWarehouseEntry[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHWarehouseEntry[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref QHWarehouseEntry QHWarehouseEntry) {
            object[] results = this.Invoke("Create", new object[] {
                        QHWarehouseEntry});
            QHWarehouseEntry = ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(QHWarehouseEntry QHWarehouseEntry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        QHWarehouseEntry}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out QHWarehouseEntry QHWarehouseEntry) {
            object[] results = this.EndInvoke(asyncResult);
            QHWarehouseEntry = ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref QHWarehouseEntry[] QHWarehouseEntry_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        QHWarehouseEntry_List});
            QHWarehouseEntry_List = ((QHWarehouseEntry[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(QHWarehouseEntry[] QHWarehouseEntry_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        QHWarehouseEntry_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out QHWarehouseEntry[] QHWarehouseEntry_List) {
            object[] results = this.EndInvoke(asyncResult);
            QHWarehouseEntry_List = ((QHWarehouseEntry[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref QHWarehouseEntry QHWarehouseEntry) {
            object[] results = this.Invoke("Update", new object[] {
                        QHWarehouseEntry});
            QHWarehouseEntry = ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(QHWarehouseEntry QHWarehouseEntry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        QHWarehouseEntry}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out QHWarehouseEntry QHWarehouseEntry) {
            object[] results = this.EndInvoke(asyncResult);
            QHWarehouseEntry = ((QHWarehouseEntry)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref QHWarehouseEntry[] QHWarehouseEntry_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        QHWarehouseEntry_List});
            QHWarehouseEntry_List = ((QHWarehouseEntry[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(QHWarehouseEntry[] QHWarehouseEntry_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        QHWarehouseEntry_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out QHWarehouseEntry[] QHWarehouseEntry_List) {
            object[] results = this.EndInvoke(asyncResult);
            QHWarehouseEntry_List = ((QHWarehouseEntry[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhwarehouseentry:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public partial class QHWarehouseEntry {
        
        private string keyField;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private string journal_Batch_NameField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        private System.DateTime registering_DateField;
        
        private bool registering_DateFieldSpecified;
        
        private string location_CodeField;
        
        private string zone_CodeField;
        
        private string bin_CodeField;
        
        private string descriptionField;
        
        private string item_NoField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal qty_BaseField;
        
        private bool qty_BaseFieldSpecified;
        
        private int source_TypeField;
        
        private bool source_TypeFieldSpecified;
        
        private Source_Subtype source_SubtypeField;
        
        private bool source_SubtypeFieldSpecified;
        
        private string source_NoField;
        
        private int source_Line_NoField;
        
        private bool source_Line_NoFieldSpecified;
        
        private int source_Subline_NoField;
        
        private bool source_Subline_NoFieldSpecified;
        
        private Source_Document source_DocumentField;
        
        private bool source_DocumentFieldSpecified;
        
        private string source_CodeField;
        
        private string reason_CodeField;
        
        private string no_SeriesField;
        
        private string bin_Type_CodeField;
        
        private decimal cubageField;
        
        private bool cubageFieldSpecified;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private string journal_Template_NameField;
        
        private string whse_Document_NoField;
        
        private Whse_Document_Type whse_Document_TypeField;
        
        private bool whse_Document_TypeFieldSpecified;
        
        private int whse_Document_Line_NoField;
        
        private bool whse_Document_Line_NoFieldSpecified;
        
        private Entry_Type entry_TypeField;
        
        private bool entry_TypeFieldSpecified;
        
        private Reference_Document reference_DocumentField;
        
        private bool reference_DocumentFieldSpecified;
        
        private string reference_NoField;
        
        private string user_IDField;
        
        private string variant_CodeField;
        
        private decimal qty_per_Unit_of_MeasureField;
        
        private bool qty_per_Unit_of_MeasureFieldSpecified;
        
        private string unit_of_Measure_CodeField;
        
        private string serial_NoField;
        
        private string lot_NoField;
        
        private System.DateTime warranty_DateField;
        
        private bool warranty_DateFieldSpecified;
        
        private System.DateTime expiration_DateField;
        
        private bool expiration_DateFieldSpecified;
        
        private string phys_Invt_Counting_Period_CodeField;
        
        private Phys_Invt_Counting_Period_Type phys_Invt_Counting_Period_TypeField;
        
        private bool phys_Invt_Counting_Period_TypeFieldSpecified;
        
        private string vF_Parent_Item_NoField;
        
        private int vF_Seq_NoField;
        
        private bool vF_Seq_NoFieldSpecified;
        
        private bool selected_ReversalField;
        
        private bool selected_ReversalFieldSpecified;
        
        private string vF_GRN_NoField;
        
        private string dateBin_CodeField;
        
        private string vendorNoField;
        
        private System.DateTime receiptDateField;
        
        private bool receiptDateFieldSpecified;
        
        private string custNoField;
        
        private System.DateTime shipmentDateField;
        
        private bool shipmentDateFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public int Entry_No {
            get {
                return this.entry_NoField;
            }
            set {
                this.entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified {
            get {
                return this.entry_NoFieldSpecified;
            }
            set {
                this.entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Journal_Batch_Name {
            get {
                return this.journal_Batch_NameField;
            }
            set {
                this.journal_Batch_NameField = value;
            }
        }
        
        /// <remarks/>
        public int Line_No {
            get {
                return this.line_NoField;
            }
            set {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified {
            get {
                return this.line_NoFieldSpecified;
            }
            set {
                this.line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Registering_Date {
            get {
                return this.registering_DateField;
            }
            set {
                this.registering_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Registering_DateSpecified {
            get {
                return this.registering_DateFieldSpecified;
            }
            set {
                this.registering_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Zone_Code {
            get {
                return this.zone_CodeField;
            }
            set {
                this.zone_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bin_Code {
            get {
                return this.bin_CodeField;
            }
            set {
                this.bin_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Item_No {
            get {
                return this.item_NoField;
            }
            set {
                this.item_NoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_Base {
            get {
                return this.qty_BaseField;
            }
            set {
                this.qty_BaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_BaseSpecified {
            get {
                return this.qty_BaseFieldSpecified;
            }
            set {
                this.qty_BaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Source_Type {
            get {
                return this.source_TypeField;
            }
            set {
                this.source_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_TypeSpecified {
            get {
                return this.source_TypeFieldSpecified;
            }
            set {
                this.source_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Source_Subtype Source_Subtype {
            get {
                return this.source_SubtypeField;
            }
            set {
                this.source_SubtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_SubtypeSpecified {
            get {
                return this.source_SubtypeFieldSpecified;
            }
            set {
                this.source_SubtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Source_No {
            get {
                return this.source_NoField;
            }
            set {
                this.source_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Source_Line_No {
            get {
                return this.source_Line_NoField;
            }
            set {
                this.source_Line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_Line_NoSpecified {
            get {
                return this.source_Line_NoFieldSpecified;
            }
            set {
                this.source_Line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Source_Subline_No {
            get {
                return this.source_Subline_NoField;
            }
            set {
                this.source_Subline_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_Subline_NoSpecified {
            get {
                return this.source_Subline_NoFieldSpecified;
            }
            set {
                this.source_Subline_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Source_Document Source_Document {
            get {
                return this.source_DocumentField;
            }
            set {
                this.source_DocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_DocumentSpecified {
            get {
                return this.source_DocumentFieldSpecified;
            }
            set {
                this.source_DocumentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Source_Code {
            get {
                return this.source_CodeField;
            }
            set {
                this.source_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Reason_Code {
            get {
                return this.reason_CodeField;
            }
            set {
                this.reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string No_Series {
            get {
                return this.no_SeriesField;
            }
            set {
                this.no_SeriesField = value;
            }
        }
        
        /// <remarks/>
        public string Bin_Type_Code {
            get {
                return this.bin_Type_CodeField;
            }
            set {
                this.bin_Type_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cubage {
            get {
                return this.cubageField;
            }
            set {
                this.cubageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CubageSpecified {
            get {
                return this.cubageFieldSpecified;
            }
            set {
                this.cubageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Journal_Template_Name {
            get {
                return this.journal_Template_NameField;
            }
            set {
                this.journal_Template_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Whse_Document_No {
            get {
                return this.whse_Document_NoField;
            }
            set {
                this.whse_Document_NoField = value;
            }
        }
        
        /// <remarks/>
        public Whse_Document_Type Whse_Document_Type {
            get {
                return this.whse_Document_TypeField;
            }
            set {
                this.whse_Document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Whse_Document_TypeSpecified {
            get {
                return this.whse_Document_TypeFieldSpecified;
            }
            set {
                this.whse_Document_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Whse_Document_Line_No {
            get {
                return this.whse_Document_Line_NoField;
            }
            set {
                this.whse_Document_Line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Whse_Document_Line_NoSpecified {
            get {
                return this.whse_Document_Line_NoFieldSpecified;
            }
            set {
                this.whse_Document_Line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Entry_Type Entry_Type {
            get {
                return this.entry_TypeField;
            }
            set {
                this.entry_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_TypeSpecified {
            get {
                return this.entry_TypeFieldSpecified;
            }
            set {
                this.entry_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Reference_Document Reference_Document {
            get {
                return this.reference_DocumentField;
            }
            set {
                this.reference_DocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reference_DocumentSpecified {
            get {
                return this.reference_DocumentFieldSpecified;
            }
            set {
                this.reference_DocumentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Reference_No {
            get {
                return this.reference_NoField;
            }
            set {
                this.reference_NoField = value;
            }
        }
        
        /// <remarks/>
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Variant_Code {
            get {
                return this.variant_CodeField;
            }
            set {
                this.variant_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_per_Unit_of_Measure {
            get {
                return this.qty_per_Unit_of_MeasureField;
            }
            set {
                this.qty_per_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_per_Unit_of_MeasureSpecified {
            get {
                return this.qty_per_Unit_of_MeasureFieldSpecified;
            }
            set {
                this.qty_per_Unit_of_MeasureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Serial_No {
            get {
                return this.serial_NoField;
            }
            set {
                this.serial_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Lot_No {
            get {
                return this.lot_NoField;
            }
            set {
                this.lot_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Warranty_Date {
            get {
                return this.warranty_DateField;
            }
            set {
                this.warranty_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Warranty_DateSpecified {
            get {
                return this.warranty_DateFieldSpecified;
            }
            set {
                this.warranty_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Expiration_DateSpecified {
            get {
                return this.expiration_DateFieldSpecified;
            }
            set {
                this.expiration_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Phys_Invt_Counting_Period_Code {
            get {
                return this.phys_Invt_Counting_Period_CodeField;
            }
            set {
                this.phys_Invt_Counting_Period_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Phys_Invt_Counting_Period_Type Phys_Invt_Counting_Period_Type {
            get {
                return this.phys_Invt_Counting_Period_TypeField;
            }
            set {
                this.phys_Invt_Counting_Period_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Phys_Invt_Counting_Period_TypeSpecified {
            get {
                return this.phys_Invt_Counting_Period_TypeFieldSpecified;
            }
            set {
                this.phys_Invt_Counting_Period_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VF_Parent_Item_No {
            get {
                return this.vF_Parent_Item_NoField;
            }
            set {
                this.vF_Parent_Item_NoField = value;
            }
        }
        
        /// <remarks/>
        public int VF_Seq_No {
            get {
                return this.vF_Seq_NoField;
            }
            set {
                this.vF_Seq_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VF_Seq_NoSpecified {
            get {
                return this.vF_Seq_NoFieldSpecified;
            }
            set {
                this.vF_Seq_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Selected_Reversal {
            get {
                return this.selected_ReversalField;
            }
            set {
                this.selected_ReversalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Selected_ReversalSpecified {
            get {
                return this.selected_ReversalFieldSpecified;
            }
            set {
                this.selected_ReversalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VF_GRN_No {
            get {
                return this.vF_GRN_NoField;
            }
            set {
                this.vF_GRN_NoField = value;
            }
        }
        
        /// <remarks/>
        public string DateBin_Code {
            get {
                return this.dateBin_CodeField;
            }
            set {
                this.dateBin_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<VendorNo>")]
        public string VendorNo {
            get {
                return this.vendorNoField;
            }
            set {
                this.vendorNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ReceiptDate>", DataType="date")]
        public System.DateTime ReceiptDate {
            get {
                return this.receiptDateField;
            }
            set {
                this.receiptDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptDateSpecified {
            get {
                return this.receiptDateFieldSpecified;
            }
            set {
                this.receiptDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CustNo {
            get {
                return this.custNoField;
            }
            set {
                this.custNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipmentDate {
            get {
                return this.shipmentDateField;
            }
            set {
                this.shipmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentDateSpecified {
            get {
                return this.shipmentDateFieldSpecified;
            }
            set {
                this.shipmentDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public enum Source_Subtype {
        
        /// <remarks/>
        _x0030_,
        
        /// <remarks/>
        _x0031_,
        
        /// <remarks/>
        _x0032_,
        
        /// <remarks/>
        _x0033_,
        
        /// <remarks/>
        _x0034_,
        
        /// <remarks/>
        _x0035_,
        
        /// <remarks/>
        _x0036_,
        
        /// <remarks/>
        _x0037_,
        
        /// <remarks/>
        _x0038_,
        
        /// <remarks/>
        _x0039_,
        
        /// <remarks/>
        _x0031_0,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public enum Source_Document {
        
        /// <remarks/>
        S_Order,
        
        /// <remarks/>
        S_Invoice,
        
        /// <remarks/>
        S_Credit_Memo,
        
        /// <remarks/>
        S_Return_Order,
        
        /// <remarks/>
        P_Order,
        
        /// <remarks/>
        P_Invoice,
        
        /// <remarks/>
        P_Credit_Memo,
        
        /// <remarks/>
        P_Return_Order,
        
        /// <remarks/>
        Inb_Transfer,
        
        /// <remarks/>
        Outb_Transfer,
        
        /// <remarks/>
        Prod_Consumption,
        
        /// <remarks/>
        Item_Jnl,
        
        /// <remarks/>
        Phys_Invt_Jnl,
        
        /// <remarks/>
        Reclass_Jnl,
        
        /// <remarks/>
        Consumption_Jnl,
        
        /// <remarks/>
        Output_Jnl,
        
        /// <remarks/>
        BOM_Jnl,
        
        /// <remarks/>
        Serv_Order,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public enum Whse_Document_Type {
        
        /// <remarks/>
        Whse_Journal,
        
        /// <remarks/>
        Receipt,
        
        /// <remarks/>
        Shipment,
        
        /// <remarks/>
        Internal_Put_away,
        
        /// <remarks/>
        Internal_Pick,
        
        /// <remarks/>
        Production,
        
        /// <remarks/>
        Whse_Phys_Inventory,
        
        /// <remarks/>
        _blank_,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public enum Entry_Type {
        
        /// <remarks/>
        Negative_Adjmt,
        
        /// <remarks/>
        Positive_Adjmt,
        
        /// <remarks/>
        Movement,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public enum Reference_Document {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Posted_Rcpt,
        
        /// <remarks/>
        Posted_P_Inv,
        
        /// <remarks/>
        Posted_Rtrn_Rcpt,
        
        /// <remarks/>
        Posted_P_Cr_Memo,
        
        /// <remarks/>
        Posted_Shipment,
        
        /// <remarks/>
        Posted_S_Inv,
        
        /// <remarks/>
        Posted_Rtrn_Shipment,
        
        /// <remarks/>
        Posted_S_Cr_Memo,
        
        /// <remarks/>
        Posted_T_Receipt,
        
        /// <remarks/>
        Posted_T_Shipment,
        
        /// <remarks/>
        Item_Journal,
        
        /// <remarks/>
        Prod,
        
        /// <remarks/>
        Put_away,
        
        /// <remarks/>
        Pick,
        
        /// <remarks/>
        Movement,
        
        /// <remarks/>
        BOM_Journal,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public enum Phys_Invt_Counting_Period_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        SKU,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public partial class QHWarehouseEntry_Filter {
        
        private QHWarehouseEntry_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public QHWarehouseEntry_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhwarehouseentry")]
    public enum QHWarehouseEntry_Fields {
        
        /// <remarks/>
        Entry_No,
        
        /// <remarks/>
        Journal_Batch_Name,
        
        /// <remarks/>
        Line_No,
        
        /// <remarks/>
        Registering_Date,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Zone_Code,
        
        /// <remarks/>
        Bin_Code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Item_No,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Qty_Base,
        
        /// <remarks/>
        Source_Type,
        
        /// <remarks/>
        Source_Subtype,
        
        /// <remarks/>
        Source_No,
        
        /// <remarks/>
        Source_Line_No,
        
        /// <remarks/>
        Source_Subline_No,
        
        /// <remarks/>
        Source_Document,
        
        /// <remarks/>
        Source_Code,
        
        /// <remarks/>
        Reason_Code,
        
        /// <remarks/>
        No_Series,
        
        /// <remarks/>
        Bin_Type_Code,
        
        /// <remarks/>
        Cubage,
        
        /// <remarks/>
        Weight,
        
        /// <remarks/>
        Journal_Template_Name,
        
        /// <remarks/>
        Whse_Document_No,
        
        /// <remarks/>
        Whse_Document_Type,
        
        /// <remarks/>
        Whse_Document_Line_No,
        
        /// <remarks/>
        Entry_Type,
        
        /// <remarks/>
        Reference_Document,
        
        /// <remarks/>
        Reference_No,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Variant_Code,
        
        /// <remarks/>
        Qty_per_Unit_of_Measure,
        
        /// <remarks/>
        Unit_of_Measure_Code,
        
        /// <remarks/>
        Serial_No,
        
        /// <remarks/>
        Lot_No,
        
        /// <remarks/>
        Warranty_Date,
        
        /// <remarks/>
        Expiration_Date,
        
        /// <remarks/>
        Phys_Invt_Counting_Period_Code,
        
        /// <remarks/>
        Phys_Invt_Counting_Period_Type,
        
        /// <remarks/>
        VF_Parent_Item_No,
        
        /// <remarks/>
        VF_Seq_No,
        
        /// <remarks/>
        Selected_Reversal,
        
        /// <remarks/>
        VF_GRN_No,
        
        /// <remarks/>
        DateBin_Code,
        
        /// <remarks/>
        _x003C_VendorNo_x003E_,
        
        /// <remarks/>
        _x003C_ReceiptDate_x003E_,
        
        /// <remarks/>
        CustNo,
        
        /// <remarks/>
        ShipmentDate,
    }
}
