//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4984.
// 
namespace QHMobile.BinQH {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BinQH_Binding", Namespace="urn:microsoft-dynamics-schemas/page/binqh")]
    public partial class BinQH_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public BinQH_Service() {
            this.Url = "http://dpmaster.dptech.local:7045/DynamicsNAVQH/WS/Qian%20Hu/Page/BinQH";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BinQH")]
        public BinQH Read(string Location_Code, string Code) {
            object[] results = this.Invoke("Read", new object[] {
                        Location_Code,
                        Code});
            return ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string Location_Code, string Code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        Location_Code,
                        Code}, callback, asyncState);
        }
        
        /// <remarks/>
        public BinQH EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BinQH")]
        public BinQH ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string recId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadByRecId", new object[] {
                        recId}, callback, asyncState);
        }
        
        /// <remarks/>
        public BinQH EndReadByRecId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BinQH[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] BinQH_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((BinQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(BinQH_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public BinQH[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BinQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref BinQH BinQH) {
            object[] results = this.Invoke("Create", new object[] {
                        BinQH});
            BinQH = ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(BinQH BinQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        BinQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out BinQH BinQH) {
            object[] results = this.EndInvoke(asyncResult);
            BinQH = ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref BinQH[] BinQH_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        BinQH_List});
            BinQH_List = ((BinQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(BinQH[] BinQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        BinQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out BinQH[] BinQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            BinQH_List = ((BinQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref BinQH BinQH) {
            object[] results = this.Invoke("Update", new object[] {
                        BinQH});
            BinQH = ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(BinQH BinQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        BinQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out BinQH BinQH) {
            object[] results = this.EndInvoke(asyncResult);
            BinQH = ((BinQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref BinQH[] BinQH_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        BinQH_List});
            BinQH_List = ((BinQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(BinQH[] BinQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        BinQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out BinQH[] BinQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            BinQH_List = ((BinQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/binqh:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/binqh", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/binqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/binqh")]
    public partial class BinQH {
        
        private string keyField;
        
        private string location_CodeField;
        
        private string codeField;
        
        private string zone_CodeField;
        
        private string descriptionField;
        
        private string bin_Type_CodeField;
        
        private string warehouse_Class_CodeField;
        
        private Block_Movement block_MovementField;
        
        private bool block_MovementFieldSpecified;
        
        private string special_Equipment_CodeField;
        
        private int bin_RankingField;
        
        private bool bin_RankingFieldSpecified;
        
        private decimal maximum_CubageField;
        
        private bool maximum_CubageFieldSpecified;
        
        private decimal maximum_WeightField;
        
        private bool maximum_WeightFieldSpecified;
        
        private bool emptyField;
        
        private bool emptyFieldSpecified;
        
        private bool cross_Dock_BinField;
        
        private bool cross_Dock_BinFieldSpecified;
        
        private bool defaultField;
        
        private bool defaultFieldSpecified;
        
        private bool assignedField;
        
        private bool assignedFieldSpecified;
        
        private bool dummyField;
        
        private bool dummyFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Zone_Code {
            get {
                return this.zone_CodeField;
            }
            set {
                this.zone_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Bin_Type_Code {
            get {
                return this.bin_Type_CodeField;
            }
            set {
                this.bin_Type_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Warehouse_Class_Code {
            get {
                return this.warehouse_Class_CodeField;
            }
            set {
                this.warehouse_Class_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Block_Movement Block_Movement {
            get {
                return this.block_MovementField;
            }
            set {
                this.block_MovementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Block_MovementSpecified {
            get {
                return this.block_MovementFieldSpecified;
            }
            set {
                this.block_MovementFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Special_Equipment_Code {
            get {
                return this.special_Equipment_CodeField;
            }
            set {
                this.special_Equipment_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Bin_Ranking {
            get {
                return this.bin_RankingField;
            }
            set {
                this.bin_RankingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bin_RankingSpecified {
            get {
                return this.bin_RankingFieldSpecified;
            }
            set {
                this.bin_RankingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Maximum_Cubage {
            get {
                return this.maximum_CubageField;
            }
            set {
                this.maximum_CubageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_CubageSpecified {
            get {
                return this.maximum_CubageFieldSpecified;
            }
            set {
                this.maximum_CubageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Maximum_Weight {
            get {
                return this.maximum_WeightField;
            }
            set {
                this.maximum_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_WeightSpecified {
            get {
                return this.maximum_WeightFieldSpecified;
            }
            set {
                this.maximum_WeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Empty {
            get {
                return this.emptyField;
            }
            set {
                this.emptyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmptySpecified {
            get {
                return this.emptyFieldSpecified;
            }
            set {
                this.emptyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Cross_Dock_Bin {
            get {
                return this.cross_Dock_BinField;
            }
            set {
                this.cross_Dock_BinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cross_Dock_BinSpecified {
            get {
                return this.cross_Dock_BinFieldSpecified;
            }
            set {
                this.cross_Dock_BinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultSpecified {
            get {
                return this.defaultFieldSpecified;
            }
            set {
                this.defaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Assigned {
            get {
                return this.assignedField;
            }
            set {
                this.assignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssignedSpecified {
            get {
                return this.assignedFieldSpecified;
            }
            set {
                this.assignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Dummy {
            get {
                return this.dummyField;
            }
            set {
                this.dummyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DummySpecified {
            get {
                return this.dummyFieldSpecified;
            }
            set {
                this.dummyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/binqh")]
    public enum Block_Movement {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Inbound,
        
        /// <remarks/>
        Outbound,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/binqh")]
    public partial class BinQH_Filter {
        
        private BinQH_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public BinQH_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/binqh")]
    public enum BinQH_Fields {
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Zone_Code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Bin_Type_Code,
        
        /// <remarks/>
        Warehouse_Class_Code,
        
        /// <remarks/>
        Block_Movement,
        
        /// <remarks/>
        Special_Equipment_Code,
        
        /// <remarks/>
        Bin_Ranking,
        
        /// <remarks/>
        Maximum_Cubage,
        
        /// <remarks/>
        Maximum_Weight,
        
        /// <remarks/>
        Empty,
        
        /// <remarks/>
        Cross_Dock_Bin,
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        Dummy,
    }
}
