//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5466.
// 
namespace QHMobile.QHSalesReceivableSetup {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QHSalesReceivableSetup_Binding", Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public partial class QHSalesReceivableSetup_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public QHSalesReceivableSetup_Service() {
            this.Url = "http://dpmaster.dptech.local:7045/DynamicsNAVQH/WS/ReplaceWithAPercentEncodedComp" +
                "anyName/Page/QHSalesReceivableSetup";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("QHSalesReceivableSetup")]
        public QHSalesReceivableSetup Read(string Primary_Key) {
            object[] results = this.Invoke("Read", new object[] {
                        Primary_Key});
            return ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string Primary_Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        Primary_Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHSalesReceivableSetup EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("QHSalesReceivableSetup")]
        public QHSalesReceivableSetup ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string recId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadByRecId", new object[] {
                        recId}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHSalesReceivableSetup EndReadByRecId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public QHSalesReceivableSetup[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] QHSalesReceivableSetup_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((QHSalesReceivableSetup[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(QHSalesReceivableSetup_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHSalesReceivableSetup[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHSalesReceivableSetup[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref QHSalesReceivableSetup QHSalesReceivableSetup) {
            object[] results = this.Invoke("Create", new object[] {
                        QHSalesReceivableSetup});
            QHSalesReceivableSetup = ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(QHSalesReceivableSetup QHSalesReceivableSetup, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        QHSalesReceivableSetup}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out QHSalesReceivableSetup QHSalesReceivableSetup) {
            object[] results = this.EndInvoke(asyncResult);
            QHSalesReceivableSetup = ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref QHSalesReceivableSetup[] QHSalesReceivableSetup_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        QHSalesReceivableSetup_List});
            QHSalesReceivableSetup_List = ((QHSalesReceivableSetup[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(QHSalesReceivableSetup[] QHSalesReceivableSetup_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        QHSalesReceivableSetup_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out QHSalesReceivableSetup[] QHSalesReceivableSetup_List) {
            object[] results = this.EndInvoke(asyncResult);
            QHSalesReceivableSetup_List = ((QHSalesReceivableSetup[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref QHSalesReceivableSetup QHSalesReceivableSetup) {
            object[] results = this.Invoke("Update", new object[] {
                        QHSalesReceivableSetup});
            QHSalesReceivableSetup = ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(QHSalesReceivableSetup QHSalesReceivableSetup, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        QHSalesReceivableSetup}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out QHSalesReceivableSetup QHSalesReceivableSetup) {
            object[] results = this.EndInvoke(asyncResult);
            QHSalesReceivableSetup = ((QHSalesReceivableSetup)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref QHSalesReceivableSetup[] QHSalesReceivableSetup_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        QHSalesReceivableSetup_List});
            QHSalesReceivableSetup_List = ((QHSalesReceivableSetup[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(QHSalesReceivableSetup[] QHSalesReceivableSetup_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        QHSalesReceivableSetup_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out QHSalesReceivableSetup[] QHSalesReceivableSetup_List) {
            object[] results = this.EndInvoke(asyncResult);
            QHSalesReceivableSetup_List = ((QHSalesReceivableSetup[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public partial class QHSalesReceivableSetup {
        
        private string keyField;
        
        private string primary_KeyField;
        
        private Discount_Posting discount_PostingField;
        
        private bool discount_PostingFieldSpecified;
        
        private Credit_Warnings credit_WarningsField;
        
        private bool credit_WarningsFieldSpecified;
        
        private bool stockout_WarningField;
        
        private bool stockout_WarningFieldSpecified;
        
        private bool shipment_on_InvoiceField;
        
        private bool shipment_on_InvoiceFieldSpecified;
        
        private bool invoice_RoundingField;
        
        private bool invoice_RoundingFieldSpecified;
        
        private bool ext_Doc_No_MandatoryField;
        
        private bool ext_Doc_No_MandatoryFieldSpecified;
        
        private string customer_NosField;
        
        private string quote_NosField;
        
        private string order_NosField;
        
        private string invoice_NosField;
        
        private string posted_Invoice_NosField;
        
        private string credit_Memo_NosField;
        
        private string posted_Credit_Memo_NosField;
        
        private string posted_Shipment_NosField;
        
        private string reminder_NosField;
        
        private string issued_Reminder_NosField;
        
        private string fin_Chrg_Memo_NosField;
        
        private string issued_Fin_Chrg_M_NosField;
        
        private string posted_Prepmt_Inv_NosField;
        
        private string posted_Prepmt_Cr_Memo_NosField;
        
        private string blanket_Order_NosField;
        
        private bool calc_Inv_DiscountField;
        
        private bool calc_Inv_DiscountFieldSpecified;
        
        private Appln_between_Currencies appln_between_CurrenciesField;
        
        private bool appln_between_CurrenciesFieldSpecified;
        
        private bool copy_Comments_Blanket_to_OrderField;
        
        private bool copy_Comments_Blanket_to_OrderFieldSpecified;
        
        private bool copy_Comments_Order_to_InvoiceField;
        
        private bool copy_Comments_Order_to_InvoiceFieldSpecified;
        
        private bool copy_Comments_Order_to_ShptField;
        
        private bool copy_Comments_Order_to_ShptFieldSpecified;
        
        private bool allow_VAT_DifferenceField;
        
        private bool allow_VAT_DifferenceFieldSpecified;
        
        private bool calc_Inv_Disc_per_VAT_IDField;
        
        private bool calc_Inv_Disc_per_VAT_IDFieldSpecified;
        
        private Logo_Position_on_Documents logo_Position_on_DocumentsField;
        
        private bool logo_Position_on_DocumentsFieldSpecified;
        
        private bool check_Prepmt_when_PostingField;
        
        private bool check_Prepmt_when_PostingFieldSpecified;
        
        private Default_Posting_Date default_Posting_DateField;
        
        private bool default_Posting_DateFieldSpecified;
        
        private Default_Quantity_to_Ship default_Quantity_to_ShipField;
        
        private bool default_Quantity_to_ShipFieldSpecified;
        
        private bool archive_Quotes_and_OrdersField;
        
        private bool archive_Quotes_and_OrdersFieldSpecified;
        
        private string posted_Return_Receipt_NosField;
        
        private bool copy_Cmts_Ret_Ord_to_Ret_RcptField;
        
        private bool copy_Cmts_Ret_Ord_to_Ret_RcptFieldSpecified;
        
        private bool copy_Cmts_Ret_Ord_to_Cr_MemoField;
        
        private bool copy_Cmts_Ret_Ord_to_Cr_MemoFieldSpecified;
        
        private string return_Order_NosField;
        
        private bool return_Receipt_on_Credit_MemoField;
        
        private bool return_Receipt_on_Credit_MemoFieldSpecified;
        
        private bool exact_Cost_Reversing_MandatoryField;
        
        private bool exact_Cost_Reversing_MandatoryFieldSpecified;
        
        private string customer_Group_Dimension_CodeField;
        
        private string salesperson_Dimension_CodeField;
        
        private string pre_GST_Prod_Posting_GroupField;
        
        private string payment_Discount_Reason_CodeField;
        
        private Components_on_Sales_Orders components_on_Sales_OrdersField;
        
        private bool components_on_Sales_OrdersFieldSpecified;
        
        private Components_on_Shipments components_on_ShipmentsField;
        
        private bool components_on_ShipmentsFieldSpecified;
        
        private Components_on_Invoices components_on_InvoicesField;
        
        private bool components_on_InvoicesFieldSpecified;
        
        private bool print_WHT_on_Credit_MemoField;
        
        private bool print_WHT_on_Credit_MemoFieldSpecified;
        
        private bool print_DialogField;
        
        private bool print_DialogFieldSpecified;
        
        private string posted_Tax_Invoice_NosField;
        
        private string posted_Tax_Credit_Memo_NosField;
        
        private string posted_Non_Tax_Invoice_NosField;
        
        private string posted_Non_Tax_Credit_Memo_NosField;
        
        private string post_Dated_Check_TemplateField;
        
        private string post_Dated_Check_BatchField;
        
        private bool incl_PDC_in_Cr_Limit_CheckField;
        
        private bool incl_PDC_in_Cr_Limit_CheckFieldSpecified;
        
        private string exportBarcodePathField;
        
        private string exportStkCodePathField;
        
        private string exportPriceLevelPathField;
        
        private System.DateTime lastExportItemDateField;
        
        private bool lastExportItemDateFieldSpecified;
        
        private bool check_Unit_PriceField;
        
        private bool check_Unit_PriceFieldSpecified;
        
        private decimal price_Control_Percentage_PercentField;
        
        private bool price_Control_Percentage_PercentFieldSpecified;
        
        private bool activate_Unit_Price_ChangeField;
        
        private bool activate_Unit_Price_ChangeFieldSpecified;
        
        private bool check_Sales_Return_PriceField;
        
        private bool check_Sales_Return_PriceFieldSpecified;
        
        private string remarks_on_Packing_WorksheetField;
        
        private string reopen_Printed_Credit_MemoField;
        
        private string reopen_Printed_Sales_ReturnField;
        
        private string vF_Item_Jnl_Adj_BatchField;
        
        private string daily_Losses_Jnl_Adj_BatchField;
        
        private string fish_Treatment_NosField;
        
        private string dummy_LocationField;
        
        private string dummy_BinField;
        
        private string pDA_Jnl_Adj_BatchField;
        
        private bool pDA_Inventory_Pick_EditableField;
        
        private bool pDA_Inventory_Pick_EditableFieldSpecified;
        
        private System.DateTime invt_Pick_Posting_DateField;
        
        private bool invt_Pick_Posting_DateFieldSpecified;
        
        private bool pDA_Time_LogField;
        
        private bool pDA_Time_LogFieldSpecified;
        
        private string change_Size_BatchField;
        
        private string picking_Supervisor_Role_IDField;
        
        private System.DateTime sales_Order_Cut_off_TimeField;
        
        private bool sales_Order_Cut_off_TimeFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Primary_Key {
            get {
                return this.primary_KeyField;
            }
            set {
                this.primary_KeyField = value;
            }
        }
        
        /// <remarks/>
        public Discount_Posting Discount_Posting {
            get {
                return this.discount_PostingField;
            }
            set {
                this.discount_PostingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Discount_PostingSpecified {
            get {
                return this.discount_PostingFieldSpecified;
            }
            set {
                this.discount_PostingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Credit_Warnings Credit_Warnings {
            get {
                return this.credit_WarningsField;
            }
            set {
                this.credit_WarningsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_WarningsSpecified {
            get {
                return this.credit_WarningsFieldSpecified;
            }
            set {
                this.credit_WarningsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Stockout_Warning {
            get {
                return this.stockout_WarningField;
            }
            set {
                this.stockout_WarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Stockout_WarningSpecified {
            get {
                return this.stockout_WarningFieldSpecified;
            }
            set {
                this.stockout_WarningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Shipment_on_Invoice {
            get {
                return this.shipment_on_InvoiceField;
            }
            set {
                this.shipment_on_InvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_on_InvoiceSpecified {
            get {
                return this.shipment_on_InvoiceFieldSpecified;
            }
            set {
                this.shipment_on_InvoiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Invoice_Rounding {
            get {
                return this.invoice_RoundingField;
            }
            set {
                this.invoice_RoundingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Invoice_RoundingSpecified {
            get {
                return this.invoice_RoundingFieldSpecified;
            }
            set {
                this.invoice_RoundingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Ext_Doc_No_Mandatory {
            get {
                return this.ext_Doc_No_MandatoryField;
            }
            set {
                this.ext_Doc_No_MandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Ext_Doc_No_MandatorySpecified {
            get {
                return this.ext_Doc_No_MandatoryFieldSpecified;
            }
            set {
                this.ext_Doc_No_MandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Nos {
            get {
                return this.customer_NosField;
            }
            set {
                this.customer_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Quote_Nos {
            get {
                return this.quote_NosField;
            }
            set {
                this.quote_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Order_Nos {
            get {
                return this.order_NosField;
            }
            set {
                this.order_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Nos {
            get {
                return this.invoice_NosField;
            }
            set {
                this.invoice_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Invoice_Nos {
            get {
                return this.posted_Invoice_NosField;
            }
            set {
                this.posted_Invoice_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Credit_Memo_Nos {
            get {
                return this.credit_Memo_NosField;
            }
            set {
                this.credit_Memo_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Credit_Memo_Nos {
            get {
                return this.posted_Credit_Memo_NosField;
            }
            set {
                this.posted_Credit_Memo_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Shipment_Nos {
            get {
                return this.posted_Shipment_NosField;
            }
            set {
                this.posted_Shipment_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Reminder_Nos {
            get {
                return this.reminder_NosField;
            }
            set {
                this.reminder_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Issued_Reminder_Nos {
            get {
                return this.issued_Reminder_NosField;
            }
            set {
                this.issued_Reminder_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Fin_Chrg_Memo_Nos {
            get {
                return this.fin_Chrg_Memo_NosField;
            }
            set {
                this.fin_Chrg_Memo_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Issued_Fin_Chrg_M_Nos {
            get {
                return this.issued_Fin_Chrg_M_NosField;
            }
            set {
                this.issued_Fin_Chrg_M_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Prepmt_Inv_Nos {
            get {
                return this.posted_Prepmt_Inv_NosField;
            }
            set {
                this.posted_Prepmt_Inv_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Prepmt_Cr_Memo_Nos {
            get {
                return this.posted_Prepmt_Cr_Memo_NosField;
            }
            set {
                this.posted_Prepmt_Cr_Memo_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Blanket_Order_Nos {
            get {
                return this.blanket_Order_NosField;
            }
            set {
                this.blanket_Order_NosField = value;
            }
        }
        
        /// <remarks/>
        public bool Calc_Inv_Discount {
            get {
                return this.calc_Inv_DiscountField;
            }
            set {
                this.calc_Inv_DiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Calc_Inv_DiscountSpecified {
            get {
                return this.calc_Inv_DiscountFieldSpecified;
            }
            set {
                this.calc_Inv_DiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Appln_between_Currencies Appln_between_Currencies {
            get {
                return this.appln_between_CurrenciesField;
            }
            set {
                this.appln_between_CurrenciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appln_between_CurrenciesSpecified {
            get {
                return this.appln_between_CurrenciesFieldSpecified;
            }
            set {
                this.appln_between_CurrenciesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Copy_Comments_Blanket_to_Order {
            get {
                return this.copy_Comments_Blanket_to_OrderField;
            }
            set {
                this.copy_Comments_Blanket_to_OrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Copy_Comments_Blanket_to_OrderSpecified {
            get {
                return this.copy_Comments_Blanket_to_OrderFieldSpecified;
            }
            set {
                this.copy_Comments_Blanket_to_OrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Copy_Comments_Order_to_Invoice {
            get {
                return this.copy_Comments_Order_to_InvoiceField;
            }
            set {
                this.copy_Comments_Order_to_InvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Copy_Comments_Order_to_InvoiceSpecified {
            get {
                return this.copy_Comments_Order_to_InvoiceFieldSpecified;
            }
            set {
                this.copy_Comments_Order_to_InvoiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Copy_Comments_Order_to_Shpt {
            get {
                return this.copy_Comments_Order_to_ShptField;
            }
            set {
                this.copy_Comments_Order_to_ShptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Copy_Comments_Order_to_ShptSpecified {
            get {
                return this.copy_Comments_Order_to_ShptFieldSpecified;
            }
            set {
                this.copy_Comments_Order_to_ShptFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Allow_VAT_Difference {
            get {
                return this.allow_VAT_DifferenceField;
            }
            set {
                this.allow_VAT_DifferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_VAT_DifferenceSpecified {
            get {
                return this.allow_VAT_DifferenceFieldSpecified;
            }
            set {
                this.allow_VAT_DifferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Calc_Inv_Disc_per_VAT_ID {
            get {
                return this.calc_Inv_Disc_per_VAT_IDField;
            }
            set {
                this.calc_Inv_Disc_per_VAT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Calc_Inv_Disc_per_VAT_IDSpecified {
            get {
                return this.calc_Inv_Disc_per_VAT_IDFieldSpecified;
            }
            set {
                this.calc_Inv_Disc_per_VAT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Logo_Position_on_Documents Logo_Position_on_Documents {
            get {
                return this.logo_Position_on_DocumentsField;
            }
            set {
                this.logo_Position_on_DocumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Logo_Position_on_DocumentsSpecified {
            get {
                return this.logo_Position_on_DocumentsFieldSpecified;
            }
            set {
                this.logo_Position_on_DocumentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Check_Prepmt_when_Posting {
            get {
                return this.check_Prepmt_when_PostingField;
            }
            set {
                this.check_Prepmt_when_PostingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Check_Prepmt_when_PostingSpecified {
            get {
                return this.check_Prepmt_when_PostingFieldSpecified;
            }
            set {
                this.check_Prepmt_when_PostingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Default_Posting_Date Default_Posting_Date {
            get {
                return this.default_Posting_DateField;
            }
            set {
                this.default_Posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Default_Posting_DateSpecified {
            get {
                return this.default_Posting_DateFieldSpecified;
            }
            set {
                this.default_Posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Default_Quantity_to_Ship Default_Quantity_to_Ship {
            get {
                return this.default_Quantity_to_ShipField;
            }
            set {
                this.default_Quantity_to_ShipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Default_Quantity_to_ShipSpecified {
            get {
                return this.default_Quantity_to_ShipFieldSpecified;
            }
            set {
                this.default_Quantity_to_ShipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Archive_Quotes_and_Orders {
            get {
                return this.archive_Quotes_and_OrdersField;
            }
            set {
                this.archive_Quotes_and_OrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Archive_Quotes_and_OrdersSpecified {
            get {
                return this.archive_Quotes_and_OrdersFieldSpecified;
            }
            set {
                this.archive_Quotes_and_OrdersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Return_Receipt_Nos {
            get {
                return this.posted_Return_Receipt_NosField;
            }
            set {
                this.posted_Return_Receipt_NosField = value;
            }
        }
        
        /// <remarks/>
        public bool Copy_Cmts_Ret_Ord_to_Ret_Rcpt {
            get {
                return this.copy_Cmts_Ret_Ord_to_Ret_RcptField;
            }
            set {
                this.copy_Cmts_Ret_Ord_to_Ret_RcptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Copy_Cmts_Ret_Ord_to_Ret_RcptSpecified {
            get {
                return this.copy_Cmts_Ret_Ord_to_Ret_RcptFieldSpecified;
            }
            set {
                this.copy_Cmts_Ret_Ord_to_Ret_RcptFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Copy_Cmts_Ret_Ord_to_Cr_Memo {
            get {
                return this.copy_Cmts_Ret_Ord_to_Cr_MemoField;
            }
            set {
                this.copy_Cmts_Ret_Ord_to_Cr_MemoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Copy_Cmts_Ret_Ord_to_Cr_MemoSpecified {
            get {
                return this.copy_Cmts_Ret_Ord_to_Cr_MemoFieldSpecified;
            }
            set {
                this.copy_Cmts_Ret_Ord_to_Cr_MemoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Return_Order_Nos {
            get {
                return this.return_Order_NosField;
            }
            set {
                this.return_Order_NosField = value;
            }
        }
        
        /// <remarks/>
        public bool Return_Receipt_on_Credit_Memo {
            get {
                return this.return_Receipt_on_Credit_MemoField;
            }
            set {
                this.return_Receipt_on_Credit_MemoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Return_Receipt_on_Credit_MemoSpecified {
            get {
                return this.return_Receipt_on_Credit_MemoFieldSpecified;
            }
            set {
                this.return_Receipt_on_Credit_MemoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Exact_Cost_Reversing_Mandatory {
            get {
                return this.exact_Cost_Reversing_MandatoryField;
            }
            set {
                this.exact_Cost_Reversing_MandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Exact_Cost_Reversing_MandatorySpecified {
            get {
                return this.exact_Cost_Reversing_MandatoryFieldSpecified;
            }
            set {
                this.exact_Cost_Reversing_MandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Group_Dimension_Code {
            get {
                return this.customer_Group_Dimension_CodeField;
            }
            set {
                this.customer_Group_Dimension_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Salesperson_Dimension_Code {
            get {
                return this.salesperson_Dimension_CodeField;
            }
            set {
                this.salesperson_Dimension_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Pre_GST_Prod_Posting_Group {
            get {
                return this.pre_GST_Prod_Posting_GroupField;
            }
            set {
                this.pre_GST_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Discount_Reason_Code {
            get {
                return this.payment_Discount_Reason_CodeField;
            }
            set {
                this.payment_Discount_Reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Components_on_Sales_Orders Components_on_Sales_Orders {
            get {
                return this.components_on_Sales_OrdersField;
            }
            set {
                this.components_on_Sales_OrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Components_on_Sales_OrdersSpecified {
            get {
                return this.components_on_Sales_OrdersFieldSpecified;
            }
            set {
                this.components_on_Sales_OrdersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Components_on_Shipments Components_on_Shipments {
            get {
                return this.components_on_ShipmentsField;
            }
            set {
                this.components_on_ShipmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Components_on_ShipmentsSpecified {
            get {
                return this.components_on_ShipmentsFieldSpecified;
            }
            set {
                this.components_on_ShipmentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Components_on_Invoices Components_on_Invoices {
            get {
                return this.components_on_InvoicesField;
            }
            set {
                this.components_on_InvoicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Components_on_InvoicesSpecified {
            get {
                return this.components_on_InvoicesFieldSpecified;
            }
            set {
                this.components_on_InvoicesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Print_WHT_on_Credit_Memo {
            get {
                return this.print_WHT_on_Credit_MemoField;
            }
            set {
                this.print_WHT_on_Credit_MemoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Print_WHT_on_Credit_MemoSpecified {
            get {
                return this.print_WHT_on_Credit_MemoFieldSpecified;
            }
            set {
                this.print_WHT_on_Credit_MemoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Print_Dialog {
            get {
                return this.print_DialogField;
            }
            set {
                this.print_DialogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Print_DialogSpecified {
            get {
                return this.print_DialogFieldSpecified;
            }
            set {
                this.print_DialogFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Tax_Invoice_Nos {
            get {
                return this.posted_Tax_Invoice_NosField;
            }
            set {
                this.posted_Tax_Invoice_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Tax_Credit_Memo_Nos {
            get {
                return this.posted_Tax_Credit_Memo_NosField;
            }
            set {
                this.posted_Tax_Credit_Memo_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Non_Tax_Invoice_Nos {
            get {
                return this.posted_Non_Tax_Invoice_NosField;
            }
            set {
                this.posted_Non_Tax_Invoice_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Posted_Non_Tax_Credit_Memo_Nos {
            get {
                return this.posted_Non_Tax_Credit_Memo_NosField;
            }
            set {
                this.posted_Non_Tax_Credit_Memo_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Post_Dated_Check_Template {
            get {
                return this.post_Dated_Check_TemplateField;
            }
            set {
                this.post_Dated_Check_TemplateField = value;
            }
        }
        
        /// <remarks/>
        public string Post_Dated_Check_Batch {
            get {
                return this.post_Dated_Check_BatchField;
            }
            set {
                this.post_Dated_Check_BatchField = value;
            }
        }
        
        /// <remarks/>
        public bool Incl_PDC_in_Cr_Limit_Check {
            get {
                return this.incl_PDC_in_Cr_Limit_CheckField;
            }
            set {
                this.incl_PDC_in_Cr_Limit_CheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Incl_PDC_in_Cr_Limit_CheckSpecified {
            get {
                return this.incl_PDC_in_Cr_Limit_CheckFieldSpecified;
            }
            set {
                this.incl_PDC_in_Cr_Limit_CheckFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ExportBarcodePath {
            get {
                return this.exportBarcodePathField;
            }
            set {
                this.exportBarcodePathField = value;
            }
        }
        
        /// <remarks/>
        public string ExportStkCodePath {
            get {
                return this.exportStkCodePathField;
            }
            set {
                this.exportStkCodePathField = value;
            }
        }
        
        /// <remarks/>
        public string ExportPriceLevelPath {
            get {
                return this.exportPriceLevelPathField;
            }
            set {
                this.exportPriceLevelPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LastExportItemDate {
            get {
                return this.lastExportItemDateField;
            }
            set {
                this.lastExportItemDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastExportItemDateSpecified {
            get {
                return this.lastExportItemDateFieldSpecified;
            }
            set {
                this.lastExportItemDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Check_Unit_Price {
            get {
                return this.check_Unit_PriceField;
            }
            set {
                this.check_Unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Check_Unit_PriceSpecified {
            get {
                return this.check_Unit_PriceFieldSpecified;
            }
            set {
                this.check_Unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Price_Control_Percentage_Percent {
            get {
                return this.price_Control_Percentage_PercentField;
            }
            set {
                this.price_Control_Percentage_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Price_Control_Percentage_PercentSpecified {
            get {
                return this.price_Control_Percentage_PercentFieldSpecified;
            }
            set {
                this.price_Control_Percentage_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Activate_Unit_Price_Change {
            get {
                return this.activate_Unit_Price_ChangeField;
            }
            set {
                this.activate_Unit_Price_ChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Activate_Unit_Price_ChangeSpecified {
            get {
                return this.activate_Unit_Price_ChangeFieldSpecified;
            }
            set {
                this.activate_Unit_Price_ChangeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Check_Sales_Return_Price {
            get {
                return this.check_Sales_Return_PriceField;
            }
            set {
                this.check_Sales_Return_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Check_Sales_Return_PriceSpecified {
            get {
                return this.check_Sales_Return_PriceFieldSpecified;
            }
            set {
                this.check_Sales_Return_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Remarks_on_Packing_Worksheet {
            get {
                return this.remarks_on_Packing_WorksheetField;
            }
            set {
                this.remarks_on_Packing_WorksheetField = value;
            }
        }
        
        /// <remarks/>
        public string Reopen_Printed_Credit_Memo {
            get {
                return this.reopen_Printed_Credit_MemoField;
            }
            set {
                this.reopen_Printed_Credit_MemoField = value;
            }
        }
        
        /// <remarks/>
        public string Reopen_Printed_Sales_Return {
            get {
                return this.reopen_Printed_Sales_ReturnField;
            }
            set {
                this.reopen_Printed_Sales_ReturnField = value;
            }
        }
        
        /// <remarks/>
        public string VF_Item_Jnl_Adj_Batch {
            get {
                return this.vF_Item_Jnl_Adj_BatchField;
            }
            set {
                this.vF_Item_Jnl_Adj_BatchField = value;
            }
        }
        
        /// <remarks/>
        public string Daily_Losses_Jnl_Adj_Batch {
            get {
                return this.daily_Losses_Jnl_Adj_BatchField;
            }
            set {
                this.daily_Losses_Jnl_Adj_BatchField = value;
            }
        }
        
        /// <remarks/>
        public string Fish_Treatment_Nos {
            get {
                return this.fish_Treatment_NosField;
            }
            set {
                this.fish_Treatment_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Dummy_Location {
            get {
                return this.dummy_LocationField;
            }
            set {
                this.dummy_LocationField = value;
            }
        }
        
        /// <remarks/>
        public string Dummy_Bin {
            get {
                return this.dummy_BinField;
            }
            set {
                this.dummy_BinField = value;
            }
        }
        
        /// <remarks/>
        public string PDA_Jnl_Adj_Batch {
            get {
                return this.pDA_Jnl_Adj_BatchField;
            }
            set {
                this.pDA_Jnl_Adj_BatchField = value;
            }
        }
        
        /// <remarks/>
        public bool PDA_Inventory_Pick_Editable {
            get {
                return this.pDA_Inventory_Pick_EditableField;
            }
            set {
                this.pDA_Inventory_Pick_EditableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PDA_Inventory_Pick_EditableSpecified {
            get {
                return this.pDA_Inventory_Pick_EditableFieldSpecified;
            }
            set {
                this.pDA_Inventory_Pick_EditableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Invt_Pick_Posting_Date {
            get {
                return this.invt_Pick_Posting_DateField;
            }
            set {
                this.invt_Pick_Posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Invt_Pick_Posting_DateSpecified {
            get {
                return this.invt_Pick_Posting_DateFieldSpecified;
            }
            set {
                this.invt_Pick_Posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PDA_Time_Log {
            get {
                return this.pDA_Time_LogField;
            }
            set {
                this.pDA_Time_LogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PDA_Time_LogSpecified {
            get {
                return this.pDA_Time_LogFieldSpecified;
            }
            set {
                this.pDA_Time_LogFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Change_Size_Batch {
            get {
                return this.change_Size_BatchField;
            }
            set {
                this.change_Size_BatchField = value;
            }
        }
        
        /// <remarks/>
        public string Picking_Supervisor_Role_ID {
            get {
                return this.picking_Supervisor_Role_IDField;
            }
            set {
                this.picking_Supervisor_Role_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Sales_Order_Cut_off_Time {
            get {
                return this.sales_Order_Cut_off_TimeField;
            }
            set {
                this.sales_Order_Cut_off_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sales_Order_Cut_off_TimeSpecified {
            get {
                return this.sales_Order_Cut_off_TimeFieldSpecified;
            }
            set {
                this.sales_Order_Cut_off_TimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Discount_Posting {
        
        /// <remarks/>
        No_Discounts,
        
        /// <remarks/>
        Invoice_Discounts,
        
        /// <remarks/>
        Line_Discounts,
        
        /// <remarks/>
        All_Discounts,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Credit_Warnings {
        
        /// <remarks/>
        Both_Warnings,
        
        /// <remarks/>
        Credit_Limit,
        
        /// <remarks/>
        Overdue_Balance,
        
        /// <remarks/>
        No_Warning,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Appln_between_Currencies {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        EMU,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Logo_Position_on_Documents {
        
        /// <remarks/>
        No_Logo,
        
        /// <remarks/>
        Left,
        
        /// <remarks/>
        Center,
        
        /// <remarks/>
        Right,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Default_Posting_Date {
        
        /// <remarks/>
        Work_Date,
        
        /// <remarks/>
        No_Date,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Default_Quantity_to_Ship {
        
        /// <remarks/>
        Remainder,
        
        /// <remarks/>
        Blank,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Components_on_Sales_Orders {
        
        /// <remarks/>
        Show,
        
        /// <remarks/>
        Do_Not_Show,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Components_on_Shipments {
        
        /// <remarks/>
        Show,
        
        /// <remarks/>
        Do_Not_Show,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum Components_on_Invoices {
        
        /// <remarks/>
        Show,
        
        /// <remarks/>
        Do_Not_Show,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public partial class QHSalesReceivableSetup_Filter {
        
        private QHSalesReceivableSetup_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public QHSalesReceivableSetup_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhsalesreceivablesetup")]
    public enum QHSalesReceivableSetup_Fields {
        
        /// <remarks/>
        Primary_Key,
        
        /// <remarks/>
        Discount_Posting,
        
        /// <remarks/>
        Credit_Warnings,
        
        /// <remarks/>
        Stockout_Warning,
        
        /// <remarks/>
        Shipment_on_Invoice,
        
        /// <remarks/>
        Invoice_Rounding,
        
        /// <remarks/>
        Ext_Doc_No_Mandatory,
        
        /// <remarks/>
        Customer_Nos,
        
        /// <remarks/>
        Quote_Nos,
        
        /// <remarks/>
        Order_Nos,
        
        /// <remarks/>
        Invoice_Nos,
        
        /// <remarks/>
        Posted_Invoice_Nos,
        
        /// <remarks/>
        Credit_Memo_Nos,
        
        /// <remarks/>
        Posted_Credit_Memo_Nos,
        
        /// <remarks/>
        Posted_Shipment_Nos,
        
        /// <remarks/>
        Reminder_Nos,
        
        /// <remarks/>
        Issued_Reminder_Nos,
        
        /// <remarks/>
        Fin_Chrg_Memo_Nos,
        
        /// <remarks/>
        Issued_Fin_Chrg_M_Nos,
        
        /// <remarks/>
        Posted_Prepmt_Inv_Nos,
        
        /// <remarks/>
        Posted_Prepmt_Cr_Memo_Nos,
        
        /// <remarks/>
        Blanket_Order_Nos,
        
        /// <remarks/>
        Calc_Inv_Discount,
        
        /// <remarks/>
        Appln_between_Currencies,
        
        /// <remarks/>
        Copy_Comments_Blanket_to_Order,
        
        /// <remarks/>
        Copy_Comments_Order_to_Invoice,
        
        /// <remarks/>
        Copy_Comments_Order_to_Shpt,
        
        /// <remarks/>
        Allow_VAT_Difference,
        
        /// <remarks/>
        Calc_Inv_Disc_per_VAT_ID,
        
        /// <remarks/>
        Logo_Position_on_Documents,
        
        /// <remarks/>
        Check_Prepmt_when_Posting,
        
        /// <remarks/>
        Default_Posting_Date,
        
        /// <remarks/>
        Default_Quantity_to_Ship,
        
        /// <remarks/>
        Archive_Quotes_and_Orders,
        
        /// <remarks/>
        Posted_Return_Receipt_Nos,
        
        /// <remarks/>
        Copy_Cmts_Ret_Ord_to_Ret_Rcpt,
        
        /// <remarks/>
        Copy_Cmts_Ret_Ord_to_Cr_Memo,
        
        /// <remarks/>
        Return_Order_Nos,
        
        /// <remarks/>
        Return_Receipt_on_Credit_Memo,
        
        /// <remarks/>
        Exact_Cost_Reversing_Mandatory,
        
        /// <remarks/>
        Customer_Group_Dimension_Code,
        
        /// <remarks/>
        Salesperson_Dimension_Code,
        
        /// <remarks/>
        Pre_GST_Prod_Posting_Group,
        
        /// <remarks/>
        Payment_Discount_Reason_Code,
        
        /// <remarks/>
        Components_on_Sales_Orders,
        
        /// <remarks/>
        Components_on_Shipments,
        
        /// <remarks/>
        Components_on_Invoices,
        
        /// <remarks/>
        Print_WHT_on_Credit_Memo,
        
        /// <remarks/>
        Print_Dialog,
        
        /// <remarks/>
        Posted_Tax_Invoice_Nos,
        
        /// <remarks/>
        Posted_Tax_Credit_Memo_Nos,
        
        /// <remarks/>
        Posted_Non_Tax_Invoice_Nos,
        
        /// <remarks/>
        Posted_Non_Tax_Credit_Memo_Nos,
        
        /// <remarks/>
        Post_Dated_Check_Template,
        
        /// <remarks/>
        Post_Dated_Check_Batch,
        
        /// <remarks/>
        Incl_PDC_in_Cr_Limit_Check,
        
        /// <remarks/>
        ExportBarcodePath,
        
        /// <remarks/>
        ExportStkCodePath,
        
        /// <remarks/>
        ExportPriceLevelPath,
        
        /// <remarks/>
        LastExportItemDate,
        
        /// <remarks/>
        Check_Unit_Price,
        
        /// <remarks/>
        Price_Control_Percentage_Percent,
        
        /// <remarks/>
        Activate_Unit_Price_Change,
        
        /// <remarks/>
        Check_Sales_Return_Price,
        
        /// <remarks/>
        Remarks_on_Packing_Worksheet,
        
        /// <remarks/>
        Reopen_Printed_Credit_Memo,
        
        /// <remarks/>
        Reopen_Printed_Sales_Return,
        
        /// <remarks/>
        VF_Item_Jnl_Adj_Batch,
        
        /// <remarks/>
        Daily_Losses_Jnl_Adj_Batch,
        
        /// <remarks/>
        Fish_Treatment_Nos,
        
        /// <remarks/>
        Dummy_Location,
        
        /// <remarks/>
        Dummy_Bin,
        
        /// <remarks/>
        PDA_Jnl_Adj_Batch,
        
        /// <remarks/>
        PDA_Inventory_Pick_Editable,
        
        /// <remarks/>
        Invt_Pick_Posting_Date,
        
        /// <remarks/>
        PDA_Time_Log,
        
        /// <remarks/>
        Change_Size_Batch,
        
        /// <remarks/>
        Picking_Supervisor_Role_ID,
        
        /// <remarks/>
        Sales_Order_Cut_off_Time,
    }
}
