//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5466.
// 
namespace QHMobile.ItemJournalQH {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItemJournalQH_Binding", Namespace="urn:microsoft-dynamics-schemas/page/itemjournalqh")]
    public partial class ItemJournalQH_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ItemJournalQH_Service() {
            this.Url = "http://dpmaster.dptech.local:7045/DynamicsNAVQH/WS/Qian%20Hu/Page/ItemJournalQH";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemJournalQH")]
        public ItemJournalQH ReadByRecId(string CurrentJnlBatchName, string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        CurrentJnlBatchName,
                        recId});
            return ((ItemJournalQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string CurrentJnlBatchName, string recId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadByRecId", new object[] {
                        CurrentJnlBatchName,
                        recId}, callback, asyncState);
        }
        
        /// <remarks/>
        public ItemJournalQH EndReadByRecId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ItemJournalQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ItemJournalQH[] ReadMultiple(string CurrentJnlBatchName, [System.Xml.Serialization.XmlElementAttribute("filter")] ItemJournalQH_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        CurrentJnlBatchName,
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ItemJournalQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(string CurrentJnlBatchName, ItemJournalQH_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        CurrentJnlBatchName,
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public ItemJournalQH[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ItemJournalQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(string CurrentJnlBatchName, ref ItemJournalQH ItemJournalQH) {
            object[] results = this.Invoke("Create", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH});
            ItemJournalQH = ((ItemJournalQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(string CurrentJnlBatchName, ItemJournalQH ItemJournalQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out ItemJournalQH ItemJournalQH) {
            object[] results = this.EndInvoke(asyncResult);
            ItemJournalQH = ((ItemJournalQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple(string CurrentJnlBatchName, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ItemJournalQH[] ItemJournalQH_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH_List});
            ItemJournalQH_List = ((ItemJournalQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(string CurrentJnlBatchName, ItemJournalQH[] ItemJournalQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out ItemJournalQH[] ItemJournalQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            ItemJournalQH_List = ((ItemJournalQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(string CurrentJnlBatchName, ref ItemJournalQH ItemJournalQH) {
            object[] results = this.Invoke("Update", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH});
            ItemJournalQH = ((ItemJournalQH)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(string CurrentJnlBatchName, ItemJournalQH ItemJournalQH, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out ItemJournalQH ItemJournalQH) {
            object[] results = this.EndInvoke(asyncResult);
            ItemJournalQH = ((ItemJournalQH)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple(string CurrentJnlBatchName, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ItemJournalQH[] ItemJournalQH_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH_List});
            ItemJournalQH_List = ((ItemJournalQH[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(string CurrentJnlBatchName, ItemJournalQH[] ItemJournalQH_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        CurrentJnlBatchName,
                        ItemJournalQH_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out ItemJournalQH[] ItemJournalQH_List) {
            object[] results = this.EndInvoke(asyncResult);
            ItemJournalQH_List = ((ItemJournalQH[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemjournalqh:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemjournalqh", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string CurrentJnlBatchName, string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        CurrentJnlBatchName,
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string CurrentJnlBatchName, string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        CurrentJnlBatchName,
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemjournalqh")]
    public partial class ItemJournalQH {
        
        private string keyField;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private System.DateTime document_DateField;
        
        private bool document_DateFieldSpecified;
        
        private string document_NoField;
        
        private string item_NoField;
        
        private string variant_CodeField;
        
        private string descriptionField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string new_Shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string new_Shortcut_Dimension_2_CodeField;
        
        private string shortcutDimCode3Field;
        
        private string newShortcutDimCode3Field;
        
        private string shortcutDimCode4Field;
        
        private string newShortcutDimCode4Field;
        
        private string shortcutDimCode5Field;
        
        private string newShortcutDimCode5Field;
        
        private string shortcutDimCode6Field;
        
        private string newShortcutDimCode6Field;
        
        private string shortcutDimCode7Field;
        
        private string newShortcutDimCode7Field;
        
        private string shortcutDimCode8Field;
        
        private string newShortcutDimCode8Field;
        
        private string location_CodeField;
        
        private string bin_CodeField;
        
        private string new_Location_CodeField;
        
        private string new_Bin_CodeField;
        
        private string salespers_Purch_CodeField;
        
        private string gen_Bus_Posting_GroupField;
        
        private string gen_Prod_Posting_GroupField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string unit_of_Measure_CodeField;
        
        private decimal unit_AmountField;
        
        private bool unit_AmountFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal indirect_Cost_PercentField;
        
        private bool indirect_Cost_PercentFieldSpecified;
        
        private decimal unit_CostField;
        
        private bool unit_CostFieldSpecified;
        
        private int applies_to_EntryField;
        
        private bool applies_to_EntryFieldSpecified;
        
        private string reason_CodeField;
        
        private string staff_Dimension_CodeField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Posting_Date {
            get {
                return this.posting_DateField;
            }
            set {
                this.posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified {
            get {
                return this.posting_DateFieldSpecified;
            }
            set {
                this.posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Document_Date {
            get {
                return this.document_DateField;
            }
            set {
                this.document_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_DateSpecified {
            get {
                return this.document_DateFieldSpecified;
            }
            set {
                this.document_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Item_No {
            get {
                return this.item_NoField;
            }
            set {
                this.item_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Variant_Code {
            get {
                return this.variant_CodeField;
            }
            set {
                this.variant_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string New_Shortcut_Dimension_1_Code {
            get {
                return this.new_Shortcut_Dimension_1_CodeField;
            }
            set {
                this.new_Shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string New_Shortcut_Dimension_2_Code {
            get {
                return this.new_Shortcut_Dimension_2_CodeField;
            }
            set {
                this.new_Shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[3]")]
        public string ShortcutDimCode3 {
            get {
                return this.shortcutDimCode3Field;
            }
            set {
                this.shortcutDimCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewShortcutDimCode[3]")]
        public string NewShortcutDimCode3 {
            get {
                return this.newShortcutDimCode3Field;
            }
            set {
                this.newShortcutDimCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[4]")]
        public string ShortcutDimCode4 {
            get {
                return this.shortcutDimCode4Field;
            }
            set {
                this.shortcutDimCode4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewShortcutDimCode[4]")]
        public string NewShortcutDimCode4 {
            get {
                return this.newShortcutDimCode4Field;
            }
            set {
                this.newShortcutDimCode4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[5]")]
        public string ShortcutDimCode5 {
            get {
                return this.shortcutDimCode5Field;
            }
            set {
                this.shortcutDimCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewShortcutDimCode[5]")]
        public string NewShortcutDimCode5 {
            get {
                return this.newShortcutDimCode5Field;
            }
            set {
                this.newShortcutDimCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[6]")]
        public string ShortcutDimCode6 {
            get {
                return this.shortcutDimCode6Field;
            }
            set {
                this.shortcutDimCode6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewShortcutDimCode[6]")]
        public string NewShortcutDimCode6 {
            get {
                return this.newShortcutDimCode6Field;
            }
            set {
                this.newShortcutDimCode6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[7]")]
        public string ShortcutDimCode7 {
            get {
                return this.shortcutDimCode7Field;
            }
            set {
                this.shortcutDimCode7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewShortcutDimCode[7]")]
        public string NewShortcutDimCode7 {
            get {
                return this.newShortcutDimCode7Field;
            }
            set {
                this.newShortcutDimCode7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[8]")]
        public string ShortcutDimCode8 {
            get {
                return this.shortcutDimCode8Field;
            }
            set {
                this.shortcutDimCode8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewShortcutDimCode[8]")]
        public string NewShortcutDimCode8 {
            get {
                return this.newShortcutDimCode8Field;
            }
            set {
                this.newShortcutDimCode8Field = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bin_Code {
            get {
                return this.bin_CodeField;
            }
            set {
                this.bin_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string New_Location_Code {
            get {
                return this.new_Location_CodeField;
            }
            set {
                this.new_Location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string New_Bin_Code {
            get {
                return this.new_Bin_CodeField;
            }
            set {
                this.new_Bin_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Salespers_Purch_Code {
            get {
                return this.salespers_Purch_CodeField;
            }
            set {
                this.salespers_Purch_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Prod_Posting_Group {
            get {
                return this.gen_Prod_Posting_GroupField;
            }
            set {
                this.gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Amount {
            get {
                return this.unit_AmountField;
            }
            set {
                this.unit_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_AmountSpecified {
            get {
                return this.unit_AmountFieldSpecified;
            }
            set {
                this.unit_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Indirect_Cost_Percent {
            get {
                return this.indirect_Cost_PercentField;
            }
            set {
                this.indirect_Cost_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Indirect_Cost_PercentSpecified {
            get {
                return this.indirect_Cost_PercentFieldSpecified;
            }
            set {
                this.indirect_Cost_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Cost {
            get {
                return this.unit_CostField;
            }
            set {
                this.unit_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_CostSpecified {
            get {
                return this.unit_CostFieldSpecified;
            }
            set {
                this.unit_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Applies_to_Entry {
            get {
                return this.applies_to_EntryField;
            }
            set {
                this.applies_to_EntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Applies_to_EntrySpecified {
            get {
                return this.applies_to_EntryFieldSpecified;
            }
            set {
                this.applies_to_EntryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Reason_Code {
            get {
                return this.reason_CodeField;
            }
            set {
                this.reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Staff_Dimension_Code {
            get {
                return this.staff_Dimension_CodeField;
            }
            set {
                this.staff_Dimension_CodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemjournalqh")]
    public partial class ItemJournalQH_Filter {
        
        private ItemJournalQH_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public ItemJournalQH_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemjournalqh")]
    public enum ItemJournalQH_Fields {
        
        /// <remarks/>
        Posting_Date,
        
        /// <remarks/>
        Document_Date,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        Item_No,
        
        /// <remarks/>
        Variant_Code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        New_Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        New_Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        ShortcutDimCode_x005B_3_x005D_,
        
        /// <remarks/>
        NewShortcutDimCode_x005B_3_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_4_x005D_,
        
        /// <remarks/>
        NewShortcutDimCode_x005B_4_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_5_x005D_,
        
        /// <remarks/>
        NewShortcutDimCode_x005B_5_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_6_x005D_,
        
        /// <remarks/>
        NewShortcutDimCode_x005B_6_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_7_x005D_,
        
        /// <remarks/>
        NewShortcutDimCode_x005B_7_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_8_x005D_,
        
        /// <remarks/>
        NewShortcutDimCode_x005B_8_x005D_,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Bin_Code,
        
        /// <remarks/>
        New_Location_Code,
        
        /// <remarks/>
        New_Bin_Code,
        
        /// <remarks/>
        Salespers_Purch_Code,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        Gen_Prod_Posting_Group,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Unit_of_Measure_Code,
        
        /// <remarks/>
        Unit_Amount,
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        Indirect_Cost_Percent,
        
        /// <remarks/>
        Unit_Cost,
        
        /// <remarks/>
        Applies_to_Entry,
        
        /// <remarks/>
        Reason_Code,
        
        /// <remarks/>
        Staff_Dimension_Code,
    }
}
