//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3623.
// 
namespace RGSMobile.SystemServiceRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SystemService_Binding", Namespace="urn:microsoft-dynamics-schemas/nav/system/")]
    public partial class SystemService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SystemService() {
            this.Url = "http://dpmaster:7047/DynamicsNAV/WS/RGS%20Enterprise%20(UAT)/SystemService";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/nav/system/:Companies", RequestNamespace="urn:microsoft-dynamics-schemas/nav/system/", ResponseElementName="Companies_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/nav/system/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string[] Companies() {
            object[] results = this.Invoke("Companies", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCompanies(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Companies", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndCompanies(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
    }
}
