//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5466.
// 
namespace QHMobile.QHBinContent {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QHBinContent_Binding", Namespace="urn:microsoft-dynamics-schemas/page/qhbincontent")]
    public partial class QHBinContent_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public QHBinContent_Service() {
            this.Url = "http://dpmaster.dptech.local:7045/DynamicsNAVQH/WS/Qian%20Hu/Page/QHBinContent";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("QHBinContent")]
        public QHBinContent Read(string Location_Code, string Bin_Code, string Item_No, string Unit_of_Measure_Code) {
            object[] results = this.Invoke("Read", new object[] {
                        Location_Code,
                        Bin_Code,
                        Item_No,
                        Unit_of_Measure_Code});
            return ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string Location_Code, string Bin_Code, string Item_No, string Unit_of_Measure_Code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        Location_Code,
                        Bin_Code,
                        Item_No,
                        Unit_of_Measure_Code}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHBinContent EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("QHBinContent")]
        public QHBinContent ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string recId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadByRecId", new object[] {
                        recId}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHBinContent EndReadByRecId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public QHBinContent[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] QHBinContent_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((QHBinContent[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(QHBinContent_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public QHBinContent[] EndReadMultiple(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((QHBinContent[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUpdated", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref QHBinContent QHBinContent) {
            object[] results = this.Invoke("Create", new object[] {
                        QHBinContent});
            QHBinContent = ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(QHBinContent QHBinContent, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        QHBinContent}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out QHBinContent QHBinContent) {
            object[] results = this.EndInvoke(asyncResult);
            QHBinContent = ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref QHBinContent[] QHBinContent_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        QHBinContent_List});
            QHBinContent_List = ((QHBinContent[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(QHBinContent[] QHBinContent_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateMultiple", new object[] {
                        QHBinContent_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out QHBinContent[] QHBinContent_List) {
            object[] results = this.EndInvoke(asyncResult);
            QHBinContent_List = ((QHBinContent[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref QHBinContent QHBinContent) {
            object[] results = this.Invoke("Update", new object[] {
                        QHBinContent});
            QHBinContent = ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(QHBinContent QHBinContent, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        QHBinContent}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out QHBinContent QHBinContent) {
            object[] results = this.EndInvoke(asyncResult);
            QHBinContent = ((QHBinContent)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref QHBinContent[] QHBinContent_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        QHBinContent_List});
            QHBinContent_List = ((QHBinContent[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(QHBinContent[] QHBinContent_List, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                        QHBinContent_List}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out QHBinContent[] QHBinContent_List) {
            object[] results = this.EndInvoke(asyncResult);
            QHBinContent_List = ((QHBinContent[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/qhbincontent:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/qhbincontent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        Key}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhbincontent")]
    public partial class QHBinContent {
        
        private string keyField;
        
        private string location_CodeField;
        
        private string zone_CodeField;
        
        private string bin_CodeField;
        
        private string bin_Type_CodeField;
        
        private Block_Movement block_MovementField;
        
        private bool block_MovementFieldSpecified;
        
        private int bin_RankingField;
        
        private bool bin_RankingFieldSpecified;
        
        private bool fixedField;
        
        private bool fixedFieldSpecified;
        
        private bool defaultField;
        
        private bool defaultFieldSpecified;
        
        private string warehouse_Class_CodeField;
        
        private string item_NoField;
        
        private decimal calcQtyUOMField;
        
        private bool calcQtyUOMFieldSpecified;
        
        private decimal quantity_BaseField;
        
        private bool quantity_BaseFieldSpecified;
        
        private decimal min_QtyField;
        
        private bool min_QtyFieldSpecified;
        
        private decimal max_QtyField;
        
        private bool max_QtyFieldSpecified;
        
        private decimal qty_per_Unit_of_MeasureField;
        
        private bool qty_per_Unit_of_MeasureFieldSpecified;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal pDA_Inv_Pick_QuantityField;
        
        private bool pDA_Inv_Pick_QuantityFieldSpecified;
        
        private string unit_of_Measure_CodeField;
        
        private string vendorNoField;
        
        private System.DateTime receiptDateField;
        
        private bool receiptDateFieldSpecified;
        
        private string custNoField;
        
        private System.DateTime shipmentDateField;
        
        private bool shipmentDateFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Zone_Code {
            get {
                return this.zone_CodeField;
            }
            set {
                this.zone_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bin_Code {
            get {
                return this.bin_CodeField;
            }
            set {
                this.bin_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bin_Type_Code {
            get {
                return this.bin_Type_CodeField;
            }
            set {
                this.bin_Type_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Block_Movement Block_Movement {
            get {
                return this.block_MovementField;
            }
            set {
                this.block_MovementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Block_MovementSpecified {
            get {
                return this.block_MovementFieldSpecified;
            }
            set {
                this.block_MovementFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Bin_Ranking {
            get {
                return this.bin_RankingField;
            }
            set {
                this.bin_RankingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bin_RankingSpecified {
            get {
                return this.bin_RankingFieldSpecified;
            }
            set {
                this.bin_RankingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Fixed {
            get {
                return this.fixedField;
            }
            set {
                this.fixedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FixedSpecified {
            get {
                return this.fixedFieldSpecified;
            }
            set {
                this.fixedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultSpecified {
            get {
                return this.defaultFieldSpecified;
            }
            set {
                this.defaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Warehouse_Class_Code {
            get {
                return this.warehouse_Class_CodeField;
            }
            set {
                this.warehouse_Class_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Item_No {
            get {
                return this.item_NoField;
            }
            set {
                this.item_NoField = value;
            }
        }
        
        /// <remarks/>
        public decimal CalcQtyUOM {
            get {
                return this.calcQtyUOMField;
            }
            set {
                this.calcQtyUOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CalcQtyUOMSpecified {
            get {
                return this.calcQtyUOMFieldSpecified;
            }
            set {
                this.calcQtyUOMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity_Base {
            get {
                return this.quantity_BaseField;
            }
            set {
                this.quantity_BaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_BaseSpecified {
            get {
                return this.quantity_BaseFieldSpecified;
            }
            set {
                this.quantity_BaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Min_Qty {
            get {
                return this.min_QtyField;
            }
            set {
                this.min_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Min_QtySpecified {
            get {
                return this.min_QtyFieldSpecified;
            }
            set {
                this.min_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Max_Qty {
            get {
                return this.max_QtyField;
            }
            set {
                this.max_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Max_QtySpecified {
            get {
                return this.max_QtyFieldSpecified;
            }
            set {
                this.max_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_per_Unit_of_Measure {
            get {
                return this.qty_per_Unit_of_MeasureField;
            }
            set {
                this.qty_per_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_per_Unit_of_MeasureSpecified {
            get {
                return this.qty_per_Unit_of_MeasureFieldSpecified;
            }
            set {
                this.qty_per_Unit_of_MeasureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PDA_Inv_Pick_Quantity {
            get {
                return this.pDA_Inv_Pick_QuantityField;
            }
            set {
                this.pDA_Inv_Pick_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PDA_Inv_Pick_QuantitySpecified {
            get {
                return this.pDA_Inv_Pick_QuantityFieldSpecified;
            }
            set {
                this.pDA_Inv_Pick_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string VendorNo {
            get {
                return this.vendorNoField;
            }
            set {
                this.vendorNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReceiptDate {
            get {
                return this.receiptDateField;
            }
            set {
                this.receiptDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptDateSpecified {
            get {
                return this.receiptDateFieldSpecified;
            }
            set {
                this.receiptDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CustNo {
            get {
                return this.custNoField;
            }
            set {
                this.custNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipmentDate {
            get {
                return this.shipmentDateField;
            }
            set {
                this.shipmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentDateSpecified {
            get {
                return this.shipmentDateFieldSpecified;
            }
            set {
                this.shipmentDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhbincontent")]
    public enum Block_Movement {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Inbound,
        
        /// <remarks/>
        Outbound,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhbincontent")]
    public partial class QHBinContent_Filter {
        
        private QHBinContent_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public QHBinContent_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/qhbincontent")]
    public enum QHBinContent_Fields {
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Zone_Code,
        
        /// <remarks/>
        Bin_Code,
        
        /// <remarks/>
        Bin_Type_Code,
        
        /// <remarks/>
        Block_Movement,
        
        /// <remarks/>
        Bin_Ranking,
        
        /// <remarks/>
        Fixed,
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Warehouse_Class_Code,
        
        /// <remarks/>
        Item_No,
        
        /// <remarks/>
        CalcQtyUOM,
        
        /// <remarks/>
        Quantity_Base,
        
        /// <remarks/>
        Min_Qty,
        
        /// <remarks/>
        Max_Qty,
        
        /// <remarks/>
        Qty_per_Unit_of_Measure,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        PDA_Inv_Pick_Quantity,
        
        /// <remarks/>
        Unit_of_Measure_Code,
        
        /// <remarks/>
        VendorNo,
        
        /// <remarks/>
        ReceiptDate,
        
        /// <remarks/>
        CustNo,
        
        /// <remarks/>
        ShipmentDate,
    }
}
